spring.application.name=T-Invest

server.servlet.context-path=/test
server.port=8998
logging.level.org.springframework.web=DEBUG
spring.docker.compose.enabled=false

invest.connector.token=${CONNECTOR_TOK}
read-only.token=${RO_TOK}
sandbox.token=${SANDBOX_TOK}
invest.connector.app.name=T-Invest-Java
invest.connector.connection.timeout=30000
invest.connector.connection.keepalive=60000
invest.connector.connection.max-message-size=16777216
invest.connector.connection.retry.max-attempts=3
invest.connector.connection.retry.wait-duration=2000
invest.connector.grpc.debug=true
invest.connector.grpc.context-fork=true
invest.connector.target=invest-public-api.tinkoff.ru:443
invest.connector.sandbox.target=sandbox-invest-public-api.tinkoff.ru:443
invest.connector.sandbox.enabled=true
invest.connector.stream.market-data.max-streams-count=16
invest.connector.stream.market-data.max-subscriptions-count=300
invest.connector.stream.inactivity-timeout=10000
invest.connector.stream.ping-delay=5000


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest
queue.name=InvestInfo

