spring.application.name=Bot

bot.name=NWOCBot
bot.token=${BOT_TOKEN}
bot.owner.chat.id=50508009


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest
queue.name=InvestInfo

spring.t-invest.host=http://localhost
spring.t-invest.port=8998
spring.t-invest.path=/test/api/investments/try-rabbit